"""Python-side Session DSL export from persisted messages.

Faithful port of ``web/features/chat/dag/dsl.ts`` (derivation rules from
``web/features/chat/trace/selectors.ts``) so ``deepmentor session trace``
produces DSL documents interchangeable with the web panel's export. The
parity contract is locked by ``tests/services/session/test_dsl_export.py``,
which compares this module's output against a fixture generated by the
TypeScript implementation (see ``fixtures/session_dsl_expected.json``).

``dsl_to_mermaid`` below is a line-by-line port of
``web/features/chat/dag/dsl-mermaid.ts`` (impl-review #66): the CLI's
``--format mermaid`` output must be byte-identical to the web panel's
"Export Mermaid" download, locked against ``fixtures/session_dsl_expected.mmd``.
"""

from __future__ import annotations

import datetime as _dt
import re
from typing import Any

DSL_VERSION = 1
GENERATOR = "deepmentor/session-dsl"
PREVIEW_LIMIT = 140

_ROOT_KEY = "null"


# ---------------------------------------------------------------------------
# Event helpers (port of trace/selectors.ts)
# ---------------------------------------------------------------------------


def _meta(event: dict[str, Any]) -> dict[str, Any]:
    return event.get("metadata") or {}


def _first_meta(events: list[dict[str, Any]], key: str) -> str:
    for event in events:
        value = _meta(event).get(key)
        if value:
            return str(value)
    return ""


def _clip(text: str) -> str:
    trimmed = text.strip()
    if len(trimmed) > PREVIEW_LIMIT:
        return f"{trimmed[:PREVIEW_LIMIT]}…"
    return trimmed


def _is_chat_loop_answer_content(event: dict[str, Any]) -> bool:
    return event.get("type") == "content" and _meta(event).get("call_kind") == "agent_loop_round"


def _is_narration_round(events: list[dict[str, Any]]) -> bool:
    return any(
        _meta(event).get("trace_kind") == "call_status"
        and _meta(event).get("call_state") == "complete"
        and _meta(event).get("call_role") == "narration"
        and _meta(event).get("answer_visible") is not True
        for event in events
    )


def _group_has_trace_substance(events: list[dict[str, Any]]) -> bool:
    narration = _is_narration_round(events)
    for event in events:
        etype = event.get("type")
        if etype in ("tool_call", "tool_result", "error"):
            return True
        if etype in ("thinking", "observation"):
            if str(event.get("content") or "").strip():
                return True
        elif etype == "progress":
            if _meta(event).get("trace_kind") != "call_status" and str(
                event.get("content") or ""
            ).strip():
                return True
        elif etype == "content":
            if (narration or not _is_chat_loop_answer_content(event)) and str(
                event.get("content") or ""
            ).strip():
                return True
    return False


def _extract_tool_name(events: list[dict[str, Any]]) -> str | None:
    for event in events:
        if event.get("type") == "tool_call":
            name = _meta(event).get("tool_name") or str(event.get("content") or "").strip()
            if name:
                return str(name)
    return None


def _extract_query(events: list[dict[str, Any]]) -> str | None:
    for event in events:
        query = _meta(event).get("query")
        if isinstance(query, str) and query.strip():
            return _clip(query)
    return None


def _extract_error(events: list[dict[str, Any]]) -> str | None:
    for event in events:
        if event.get("type") == "error":
            text = _clip(str(event.get("content") or ""))
            if text:
                return text
    return None


def _get_call_provider(events: list[dict[str, Any]]) -> str:
    for event in events:
        meta = _meta(event)
        nested = meta.get("tool_metadata")
        value = ""
        if isinstance(nested, dict) and isinstance(nested.get("provider"), str):
            value = nested["provider"]
        if not value:
            value = meta.get("provider") or ""
        trimmed = str(value).strip()
        if trimmed and trimmed != "none":
            return trimmed
    return ""


def _last_call_state(events: list[dict[str, Any]]) -> str | None:
    state = None
    for event in events:
        value = _meta(event).get("call_state")
        if value:
            state = str(value)
    return state


def _extract_duration_ms(events: list[dict[str, Any]]) -> int | None:
    timestamps = [
        event["timestamp"]
        for event in events
        if isinstance(event.get("timestamp"), (int, float))
    ]
    if not timestamps:
        return None
    duration = max(timestamps) - min(timestamps)
    return int(duration) if duration > 0 else None


# ---------------------------------------------------------------------------
# Call groups (port of aggregate.ts walkCallGroups / materializeCalls)
# ---------------------------------------------------------------------------


def _walk_call_groups(events: list[dict[str, Any]] | None) -> list[dict[str, Any]]:
    if not events:
        return []
    groups: dict[str, list[dict[str, Any]]] = {}
    for event in events:
        call_id = str(_meta(event).get("call_id") or "")
        if not call_id:
            continue
        groups.setdefault(call_id, []).append(event)

    result: list[dict[str, Any]] = []
    for call_id, group_events in groups.items():
        kind = _first_meta(group_events, "call_kind")
        if kind == "llm_final_response":
            continue
        if any(_meta(e).get("absorbed_into_final") is True for e in group_events):
            continue
        if not _group_has_trace_substance(group_events):
            continue

        group = _first_meta(group_events, "trace_group")
        role = _first_meta(group_events, "trace_role")
        if kind == "tool_planning" or group == "tool_call":
            node_kind = "tool_call"
        elif role == "retrieve":
            node_kind = "retrieve"
        else:
            node_kind = "round"

        subagents: list[dict[str, Any]] = []
        if node_kind == "tool_call":
            seen: set[str] = set()
            for event in group_events:
                meta = _meta(event)
                if meta.get("subagent_name") is None:
                    continue
                name = str(meta["subagent_name"])
                consult_index = meta.get("consult_index")
                consult_index = consult_index if isinstance(consult_index, int) else None
                key = f"{name}:{'' if consult_index is None else consult_index}"
                if key in seen:
                    continue
                seen.add(key)
                subagents.append({"name": name, "consult_index": consult_index})

        result.append(
            {
                "kind": node_kind,
                "call_id": call_id,
                "events": group_events,
                "subagents": subagents,
            }
        )
    return result


def _build_call_tree(events: list[dict[str, Any]] | None) -> list[dict[str, Any]]:
    """Materialize the message's call tree as nested DSL call entries."""
    # First pass: flat node metas (mirrors materializeCalls).
    flat: list[dict[str, Any]] = []  # {kind, meta, children: []}
    seq = 0
    n_round = 0
    for group in _walk_call_groups(events):
        meta: dict[str, Any] = {
            "call_id": group["call_id"],
            "call_kind": _first_meta(group["events"], "call_kind") or None,
            "call_state": _last_call_state(group["events"]),
            "trace_group": _first_meta(group["events"], "trace_group") or None,
            "provider": _get_call_provider(group["events"]) or None,
            "tool_name": (
                _extract_tool_name(group["events"]) if group["kind"] == "tool_call" else None
            ),
            "query": _extract_query(group["events"]),
            "round_index": n_round if group["kind"] == "round" else None,
            "duration_ms": _extract_duration_ms(group["events"]),
            "error": _extract_error(group["events"]),
        }
        flat.append({"kind": group["kind"], "meta": meta, "children": []})
        seq += 1
        if group["kind"] == "round":
            n_round += 1
        for sub in group["subagents"]:
            flat.append(
                {
                    "kind": "subagent",
                    "meta": {
                        "call_id": group["call_id"],
                        "subagent_name": sub["name"],
                        "consult_index": sub["consult_index"],
                        "call_state": _last_call_state(group["events"]),
                        "duration_ms": _extract_duration_ms(group["events"]),
                    },
                    "children": [],
                }
            )
            seq += 1

    # Second pass: nest per the IR parent rules (round ← message, tool ←
    # current round, retrieve/subagent ← current tool or round).
    roots: list[dict[str, Any]] = []
    current_round: dict[str, Any] | None = None
    current_tool: dict[str, Any] | None = None
    for node in flat:
        if node["kind"] == "round":
            roots.append(node)
            current_round = node
            current_tool = None
        elif node["kind"] == "tool_call":
            parent = current_round if current_round is not None else None
            if parent is None:
                roots.append(node)
            else:
                parent["children"].append(node)
            current_tool = node
        elif node["kind"] == "subagent":
            if current_tool is not None:
                current_tool["children"].append(node)
            elif current_round is not None:
                current_round["children"].append(node)
            else:
                roots.append(node)
        else:  # retrieve
            if current_tool is not None:
                current_tool["children"].append(node)
            elif current_round is not None:
                current_round["children"].append(node)
            else:
                roots.append(node)
    return roots


# ---------------------------------------------------------------------------
# Visible path (port of lib/message-branches.ts buildVisiblePath)
# ---------------------------------------------------------------------------


def _parent_key(parent_id: int | None) -> str:
    return _ROOT_KEY if parent_id is None else str(parent_id)


def _visible_path(
    messages: list[dict[str, Any]],
    selected: dict[str, int] | None = None,
) -> tuple[list[dict[str, Any]], dict[int, dict[str, Any]]]:
    children_by_parent: dict[str, list[dict[str, Any]]] = {}
    for message in messages:
        msg_id = message.get("id")
        if msg_id is None:
            continue
        key = _parent_key(message.get("parent_message_id"))
        children_by_parent.setdefault(key, []).append(message)
    for children in children_by_parent.values():
        # Persisted rows carry positive autoincrement ids; ascending order is
        # the creation order (frontend siblingRank also floats optimistic
        # negative ids first, which never occur in the store).
        children.sort(key=lambda m: m["id"])

    start = (
        _ROOT_KEY
        if children_by_parent.get(_ROOT_KEY)
        else _fallback_start(messages)
    )
    visible: list[dict[str, Any]] = []
    siblings: dict[int, dict[str, Any]] = {}
    guard: set[str] = set()
    current = start
    while len(guard) < 10_000:
        if current in guard:
            break
        guard.add(current)
        children = children_by_parent.get(current)
        if not children:
            break
        if len(children) == 1:
            chosen = children[0]
        else:
            selected_id = (selected or {}).get(current)
            chosen = next((c for c in children if c["id"] == selected_id), children[-1])
        visible.append(chosen)
        if len(children) > 1:
            siblings[chosen["id"]] = {
                "total": len(children),
                "index": 1 + next(i for i, c in enumerate(children) if c["id"] == chosen["id"]),
                "sibling_ids": [c["id"] for c in children],
                "parent_id": chosen.get("parent_message_id"),
            }
        current = str(chosen["id"])
    # deep_research two-turn pairs are merged on the *visible* path (#63/#64):
    # the followup assistant is dropped and its events spliced into the
    # outline-preview parent, mirroring the web aggregation exactly.
    return _merge_deep_research_pairs(visible), siblings


def _fallback_start(messages: list[dict[str, Any]]) -> str:
    # Port of walkStartKey: if no true roots, start from the first orphan
    # (parent id not present among message ids).
    known = {m["id"] for m in messages if m.get("id") is not None}
    for message in messages:
        msg_id = message.get("id")
        if msg_id is None:
            continue
        parent = message.get("parent_message_id")
        if parent is None or parent not in known:
            return _parent_key(parent)
    return _ROOT_KEY


# ---------------------------------------------------------------------------
# deep_research two-turn merge (port of aggregate.ts mergeDeepResearchPairs,
# pairing rules identical to ChatMessageList.deepResearchMergeMap — #64)
# ---------------------------------------------------------------------------


def _is_confirmed_research_followup(events: list[dict[str, Any]] | None) -> bool:
    if not events:
        return False
    for event in events:
        if event.get("type") == "result" and _meta(event).get("outline_preview") is True:
            return False
    return any(event.get("stage") in ("researching", "reporting") for event in events)


def _has_outline_preview(events: list[dict[str, Any]] | None) -> bool:
    return any(
        event.get("type") == "result" and bool(_meta(event).get("outline_preview"))
        for event in (events or [])
    )


def _merge_deep_research_pairs(
    messages: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    followup_ids: set[int] = set()
    merged_events: dict[int, list[dict[str, Any]]] = {}
    for i, message in enumerate(messages):
        if (
            message.get("role") != "assistant"
            or message.get("capability") != "deep_research"
        ):
            continue
        if not _has_outline_preview(message.get("events")):
            continue
        followup_index = next(
            (
                j
                for j in range(i + 1, len(messages))
                if messages[j].get("role") == "assistant"
                and messages[j].get("capability") == "deep_research"
            ),
            -1,
        )
        if followup_index == -1:
            continue
        followup = messages[followup_index]
        if not _is_confirmed_research_followup(followup.get("events")):
            continue
        merged_events[i] = [
            *(message.get("events") or []),
            *(followup.get("events") or []),
        ]
        if followup.get("id") is not None:
            followup_ids.add(followup["id"])
    if not followup_ids:
        return messages
    return [
        {**m, "events": merged_events[i]} if i in merged_events else m
        for i, m in enumerate(messages)
        if m.get("id") is None or m["id"] not in followup_ids
    ]


# ---------------------------------------------------------------------------
# DSL assembly (port of dsl.ts convertTrace / collectBranches)
# ---------------------------------------------------------------------------


class _Writer:
    def __init__(self, stable: bool, normalize_ids: bool, include_text: bool) -> None:
        self.stable = stable
        self.normalize_ids = normalize_ids
        self.include_text = include_text


def _convert_calls(
    roots: list[dict[str, Any]],
    writer: _Writer,
    counters: dict[str, int],
    prefix: str,
) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for root in roots:
        counters["call"] += 1
        meta = root["meta"]
        entry: dict[str, Any] = {
            "node": (
                f"{prefix}turn:{counters['message']}.{counters['call']}"
                if writer.normalize_ids
                else f"call:{meta['call_id']}:{root['kind']}:{counters['call'] - 1}"
            ),
            "kind": root["kind"],
        }
        if root["kind"] == "subagent":
            if meta.get("subagent_name"):
                entry["subagent_name"] = meta["subagent_name"]
            if meta.get("consult_index") is not None:
                entry["consult_index"] = meta["consult_index"]
        else:
            if meta.get("tool_name"):
                entry["tool"] = meta["tool_name"]
            if meta.get("round_index") is not None:
                entry["round_index"] = meta["round_index"]
            if meta.get("query"):
                entry["query"] = meta["query"]
        if meta.get("provider"):
            entry["provider"] = meta["provider"]
        if meta.get("call_state"):
            entry["state"] = meta["call_state"]
        if not writer.stable and meta.get("duration_ms") is not None:
            entry["duration_ms"] = meta["duration_ms"]
        if not writer.stable and meta.get("error"):
            entry["error"] = meta["error"]
        children = _convert_calls(root["children"], writer, counters, prefix)
        if children:
            entry["calls"] = children
        entries.append(entry)
    return entries


def _convert_trace(
    messages: list[dict[str, Any]],
    writer: _Writer,
    start_index: int = 0,
    allow_branches: bool = True,
    reuse: tuple[list[dict[str, Any]], dict[int, dict[str, Any]], str] | None = None,
) -> list[dict[str, Any]]:
    if reuse is not None:
        visible, siblings, prefix = reuse
    else:
        visible, siblings = _visible_path(messages)
        prefix = ""

    entries: list[dict[str, Any]] = []
    counters = {"message": 0, "call": 0}
    for index in range(start_index, len(visible)):
        message = visible[index]
        if message.get("role") == "system":
            continue
        msg_id = message.get("id")
        if isinstance(msg_id, int) and msg_id < 0:
            continue
        counters["message"] += 1
        counters["call"] = 0

        entry: dict[str, Any] = {
            "node": (
                f"{prefix}turn:{counters['message']}" if writer.normalize_ids else f"msg:{msg_id}"
            ),
            "kind": message["role"],
        }
        if writer.include_text and message.get("role") == "user":
            preview = _clip(str(message.get("content") or ""))
            if preview:
                entry["text_preview"] = preview
        if message.get("capability"):
            entry["capability"] = message["capability"]

        info = siblings.get(msg_id) if msg_id is not None else None
        if info and info["total"] > 1:
            entry["branch"] = {"index": info["index"], "total": info["total"]}
            # Branches are collected one level deep only — mirrors the web
            # serializer (impl-review D1).
            if allow_branches:
                branches = _collect_branches(messages, msg_id, info, writer)
                if branches:
                    entry["branches"] = branches

        if message.get("role") == "assistant":
            calls = _convert_calls(_build_call_tree(message.get("events")), writer, counters, prefix)
            if calls:
                entry["calls"] = calls
        entries.append(entry)
    return entries


def _collect_branches(
    messages: list[dict[str, Any]],
    chosen_id: int | None,
    info: dict[str, Any],
    writer: _Writer,
) -> list[dict[str, Any]]:
    key = _parent_key(info["parent_id"])
    branches: list[dict[str, Any]] = []
    for position, sibling_id in enumerate(info["sibling_ids"]):
        if sibling_id == chosen_id:
            continue
        override = {key: sibling_id}
        sub_visible, sub_siblings = _visible_path(messages, override)
        start = next(
            (i for i, m in enumerate(sub_visible) if m.get("id") == sibling_id), -1
        )
        if start < 0:
            continue
        trace = _convert_trace(
            messages,
            writer,
            start_index=start,
            allow_branches=False,
            reuse=(sub_visible, sub_siblings, f"b{position + 1}:"),
        )
        branches.append({"selected": False, "trace": trace})
    return branches


def build_session_dsl(
    messages: list[dict[str, Any]],
    *,
    stable: bool = False,
    normalize_ids: bool = False,
    include_text: bool = True,
    session_id: str = "",
) -> dict[str, Any]:
    """Build a Session DSL document from persisted session messages.

    ``messages`` follows the session-store shape (``id``, ``role``,
    ``content``, ``capability``, ``events``, ``parent_message_id``).
    """
    writer = _Writer(stable=stable, normalize_ids=normalize_ids, include_text=include_text)
    trace = _convert_trace(messages, writer)
    doc: dict[str, Any] = {
        "version": DSL_VERSION,
        "generator": GENERATOR,
        "trace": trace,
    }
    if not stable:
        doc["session"] = {
            "id": session_id,
            "exported_at": _dt.datetime.now(_dt.timezone.utc).isoformat().replace("+00:00", "Z"),
            "turn_count": len(trace),
        }
    return doc


# ---------------------------------------------------------------------------
# Mermaid codegen (port of dsl-mermaid.ts, #66 — byte-level parity contract)
# ---------------------------------------------------------------------------

MERMAID_LABEL_LIMIT = 48


def _sanitize_mermaid_id(node_id: str, used: set[str]) -> str:
    """DSL ids contain ``:`` which mermaid ids reject — sanitize and dedupe."""
    base = re.sub(r"[^A-Za-z0-9_-]", "_", node_id) or "n"
    candidate = base
    suffix = 1
    while candidate in used:
        candidate = f"{base}_{suffix}"
        suffix += 1
    used.add(candidate)
    return candidate


def _sanitize_mermaid_label(text: str | None) -> str:
    """Scrub ``"``/``#``/newlines that break mermaid quoted labels, then clip."""
    if not text:
        return ""
    flat = re.sub(r'["#\r\n]', " ", text).strip()
    # NOTE: JS slices by UTF-16 code units; astral-plane characters (emoji)
    # past the limit would clip one position earlier on the web side. The
    # parity fixture stays in the BMP, so the ports agree where it matters.
    return f"{flat[:MERMAID_LABEL_LIMIT]}..." if len(flat) > MERMAID_LABEL_LIMIT else flat


def _trace_label(entry: dict[str, Any]) -> str:
    if entry.get("kind") == "user":
        return f"User: {_sanitize_mermaid_label(entry.get('text_preview'))}"
    capability = entry.get("capability")
    suffix = f" ({_sanitize_mermaid_label(capability)})" if capability else ""
    return f"Assistant{suffix}"


def _call_label(entry: dict[str, Any]) -> str:
    kind = entry.get("kind")
    if kind == "round":
        round_index = entry.get("round_index")
        return f"Round {round_index + 1}" if round_index is not None else "Round"
    if kind == "retrieve":
        return f"Retrieve: {_sanitize_mermaid_label(entry.get('query'))}"
    if kind == "subagent":
        return f"Subagent: {_sanitize_mermaid_label(entry.get('subagent_name'))}"
    return f"Tool: {_sanitize_mermaid_label(entry.get('tool'))}"


class _MermaidContext:
    def __init__(self) -> None:
        self.lines: list[str] = ["flowchart TD"]
        self.used: set[str] = set()
        self.id_by_node: dict[str, str] = {}

    def register_node(self, node_id: str, label: str) -> str:
        mermaid_id = _sanitize_mermaid_id(node_id, self.used)
        self.id_by_node[node_id] = mermaid_id
        self.lines.append(f'    {mermaid_id}["{label}"]')
        return mermaid_id


def _render_calls(ctx: _MermaidContext, calls: list[dict[str, Any]], parent_node: str) -> None:
    parent = parent_node
    for call in calls:
        call_id = ctx.register_node(call["node"], _call_label(call))
        ctx.lines.append(f"    {parent} --> {call_id}")
        if call.get("calls"):
            _render_calls(ctx, call["calls"], call_id)
        parent = call_id


def _render_branch(
    ctx: _MermaidContext,
    branch: dict[str, Any],
    position: int,
    fork_node: str,
) -> None:
    # Dashed alternative-path edge; the branch's own chain renders inline
    # (single-level expansion is already guaranteed by the DSL itself).
    trace = branch.get("trace") or []
    if not trace:
        return
    first = trace[0]
    first_id = _sanitize_mermaid_id(first["node"], ctx.used)
    ctx.id_by_node[first["node"]] = first_id
    ctx.lines.append(f'    {first_id}["{_trace_label(first)}"]')
    ctx.lines.append(f'    {fork_node} -. "branch {position}" .-> {first_id}')
    if first.get("calls"):
        _render_calls(ctx, first["calls"], first_id)
    _render_trace_chain(ctx, trace[1:], first_id)


def _render_trace_chain(
    ctx: _MermaidContext,
    trace: list[dict[str, Any]],
    start_node: str | None,
) -> str | None:
    prev = start_node
    for entry in trace:
        node_id = ctx.register_node(entry["node"], _trace_label(entry))
        if prev:
            ctx.lines.append(f"    {prev} --> {node_id}")
        if entry.get("calls"):
            _render_calls(ctx, entry["calls"], node_id)
        for position, branch in enumerate(entry.get("branches") or []):
            _render_branch(ctx, branch, position + 1, node_id)
        prev = node_id
    return prev


def dsl_to_mermaid(doc: dict[str, Any]) -> str:
    """Render a Session DSL document as a ``flowchart TD`` diagram."""
    ctx = _MermaidContext()
    _render_trace_chain(ctx, doc.get("trace") or [], None)
    return "\n".join(ctx.lines) + "\n"
