"""Session DSL export — Python port parity with the web serializer.

The parity fixture (``fixtures/session_dsl_expected.json``) is generated by
the TypeScript implementation (``web/features/chat/dag/dsl.ts``) — regenerate
it with tsx if the web derivation rules ever change:

    npx tsx <script that builds store-shaped fixture messages and calls
    buildSessionDslDocument>

If this test fails after a web-side change, the fixture must be regenerated
AND this port updated in the same commit (impl-review #53).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from deepmentor.services.session.dsl_export import build_session_dsl, dsl_to_mermaid

FIXTURE = Path(__file__).parent / "fixtures" / "session_dsl_expected.json"
MERMAID_FIXTURE = Path(__file__).parent / "fixtures" / "session_dsl_expected.mmd"


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_parity_stable_normalized_matches_web_serializer() -> None:
    fixture = _load_fixture()
    doc = build_session_dsl(
        fixture["input_messages"], stable=True, normalize_ids=True
    )
    assert doc == fixture["expected"]["stable_normalized"]


def test_parity_raw_ids_match_web_serializer() -> None:
    fixture = _load_fixture()
    doc = build_session_dsl(fixture["input_messages"], session_id="s1")
    expected = dict(fixture["expected"]["raw"])
    # exported_at is wall-clock on both sides — compare everything else.
    assert doc["session"]["id"] == expected["session"]["id"]
    assert doc["session"]["turn_count"] == expected["session"]["turn_count"]
    del doc["session"]["exported_at"]
    del expected["session"]["exported_at"]
    assert doc == expected


def _msg(
    msg_id: int,
    role: str,
    parent: int | None,
    events: list[dict] | None = None,
    content: str = "",
    capability: str = "",
) -> dict:
    return {
        "id": msg_id,
        "role": role,
        "content": content,
        "capability": capability,
        "events": events or [],
        "parent_message_id": parent,
    }


def _ev(
    etype: str,
    metadata: dict,
    content: str = "",
    timestamp: int = 1,
    stage: str = "exploring",
) -> dict:
    return {
        "type": etype,
        "source": "chat",
        "stage": stage,
        "content": content,
        "metadata": metadata,
        "timestamp": timestamp,
    }


def test_stable_strips_volatile_fields_and_session_block() -> None:
    events = [
        _ev("thinking", {"call_id": "r1", "call_kind": "agent_loop_round"}, "plan", 1),
        _ev("tool_call", {"call_id": "t1", "trace_group": "tool_call", "tool_name": "rag"}, "rag", 2),
        _ev("tool_result", {"call_id": "t1", "trace_group": "tool_call"}, "ok", 5),
    ]
    messages = [
        _msg(1, "user", None, content="hi"),
        _msg(2, "assistant", 1, events=events),
    ]
    plain = build_session_dsl(messages)
    stable = build_session_dsl(messages, stable=True)
    assert "session" in plain
    assert "session" not in stable
    calls = plain["trace"][1]["calls"]
    assert calls[0]["kind"] == "round"  # single event → no duration
    tool = calls[0]["calls"][0]  # nested under the round (tree shape)
    assert tool["duration_ms"] == 3  # t1: timestamps 2..5
    stable_calls = stable["trace"][1]["calls"]
    assert all(
        "duration_ms" not in c
        for call in stable_calls
        for c in [call, *call.get("calls", [])]
    )


def test_include_text_false_removes_previews() -> None:
    messages = [
        _msg(1, "user", None, content="secret question"),
        _msg(2, "assistant", 1),
    ]
    assert build_session_dsl(messages)["trace"][0]["text_preview"] == "secret question"
    assert "text_preview" not in build_session_dsl(messages, include_text=False)["trace"][0]


def test_normalize_ids_renumber_positionally() -> None:
    events = [
        _ev("thinking", {"call_id": "r1", "call_kind": "agent_loop_round"}, "plan", 1),
    ]
    messages = [
        _msg(1, "user", None, content="hi"),
        _msg(2, "assistant", 1, events=events),
    ]
    doc = build_session_dsl(messages, normalize_ids=True)
    assert [t["node"] for t in doc["trace"]] == ["turn:1", "turn:2"]
    assert doc["trace"][1]["calls"][0]["node"] == "turn:2.1"


def test_branch_export_uses_sibling_position_prefix() -> None:
    # Root fork: user 1 (→ assistant 2) vs user 3 (→ assistant 4).
    # Default selection = latest sibling (3), branch covers 1 → 2.
    events = [
        _ev("thinking", {"call_id": "r1", "call_kind": "agent_loop_round"}, "plan", 1),
    ]
    messages = [
        _msg(1, "user", None, content="original"),
        _msg(2, "assistant", 1, events=events),
        _msg(3, "user", None, content="edited"),
        _msg(4, "assistant", 3, events=events),
    ]
    doc = build_session_dsl(messages, normalize_ids=True)
    assert [t["node"] for t in doc["trace"]] == ["turn:1", "turn:2"]
    assert doc["trace"][0]["branch"] == {"index": 2, "total": 2}
    branch = doc["trace"][0]["branches"][0]
    assert [t["node"] for t in branch["trace"]] == ["b1:turn:1", "b1:turn:2"]
    # one level deep only: no nested branches inside the branch trace
    assert all("branches" not in t for t in branch["trace"])


def test_group_filters_llm_final_response_and_absorbed() -> None:
    events = [
        _ev("thinking", {"call_id": "r1", "call_kind": "agent_loop_round"}, "plan", 1),
        _ev("content", {"call_id": "f1", "call_kind": "llm_final_response"}, "final answer", 2),
        _ev("content", {"call_id": "a1", "absorbed_into_final": True}, "absorbed", 3),
    ]
    messages = [_msg(1, "user", None, content="hi"), _msg(2, "assistant", 1, events=events)]
    doc = build_session_dsl(messages)
    calls = doc["trace"][1]["calls"]
    assert [c["call_id"] if "call_id" in c else c["node"] for c in calls] == [
        "call:r1:round:0"
    ]


def test_narration_only_rounds_are_skipped() -> None:
    events = [
        _ev(
            "progress",
            {
                "call_id": "n1",
                "call_kind": "agent_loop_round",
                "trace_kind": "call_status",
                "call_state": "complete",
                "call_role": "narration",
            },
            "",
            1,
        ),
    ]
    messages = [_msg(1, "user", None, content="hi"), _msg(2, "assistant", 1, events=events)]
    doc = build_session_dsl(messages)
    assert doc["trace"][1].get("calls") is None


def test_empty_messages_produce_empty_trace() -> None:
    doc = build_session_dsl([])
    assert doc["trace"] == []
    assert doc["version"] == 1
    assert doc["generator"] == "deepmentor/session-dsl"


def test_deep_research_pair_merges_on_visible_path() -> None:
    # module 12: followup assistant dropped, events spliced into the parent.
    outline = [
        _ev("thinking", {"call_id": "r1", "call_kind": "agent_loop_round"}, "rephrase", 1),
        _ev("result", {"outline_preview": True}, "outline", 2),
    ]
    followup = [
        _ev("thinking", {"call_id": "r2", "call_kind": "agent_loop_round"}, "search", 3, "researching"),
        _ev("content", {"call_id": "r2"}, "report", 4, "reporting"),
    ]
    messages = [
        _msg(1, "user", None, content="research this"),
        _msg(2, "assistant", 1, events=outline, capability="deep_research"),
        _msg(3, "user", 2, content="ack"),
        _msg(4, "assistant", 3, events=followup, capability="deep_research"),
        _msg(5, "user", 4, content="thanks"),
    ]
    doc = build_session_dsl(messages, stable=True, normalize_ids=True)
    assert [t["kind"] for t in doc["trace"]] == ["user", "assistant", "user", "user"]
    calls = doc["trace"][1]["calls"]
    assert [c["node"] for c in calls] == ["turn:2.1", "turn:2.2"]  # both turns' rounds


def test_deep_research_pair_requires_confirmed_followup() -> None:
    # followup without researching/reporting stage → no merge, two assistants
    messages = [
        _msg(1, "user", None, content="research this"),
        _msg(2, "assistant", 1, events=[_ev("result", {"outline_preview": True}, "o")], capability="deep_research"),
        _msg(3, "user", 2, content="ack"),
        _msg(4, "assistant", 3, events=[_ev("thinking", {"call_id": "x"}, "nope")], capability="deep_research"),
    ]
    doc = build_session_dsl(messages)
    assert len([t for t in doc["trace"] if t["kind"] == "assistant"]) == 2


def test_parity_mermaid_matches_web_codegen() -> None:
    # #66: byte-level parity with the web "Export Mermaid" download. The
    # fixture is generated by tsx from the same input messages
    # (fixtures/generate_parity.mts) — regenerate both together.
    fixture = _load_fixture()
    doc = build_session_dsl(fixture["input_messages"], stable=True, normalize_ids=True)
    assert dsl_to_mermaid(doc) == MERMAID_FIXTURE.read_text(encoding="utf-8")


def test_mermaid_empty_document_is_header_only() -> None:
    assert dsl_to_mermaid({"version": 1, "trace": []}) == "flowchart TD\n"


def test_mermaid_label_sanitization_and_clip() -> None:
    doc = {
        "version": 1,
        "trace": [
            {
                "node": "turn:1",
                "kind": "user",
                "text_preview": 'quote " hash # newline\nend ' + "x" * 60,
            },
            {"node": "turn:2", "kind": "assistant", "capability": "deep_solve"},
        ],
    }
    lines = dsl_to_mermaid(doc).splitlines()
    # `"`/`#`/newline scrubbed to spaces; clipped at 48 chars + ellipsis
    expected_label = "User: quote   hash   newline end " + "x" * 21 + "..."
    assert lines[1] == f'    turn_1["{expected_label}"]'
    assert lines[2] == '    turn_2["Assistant (deep_solve)"]'


def test_mermaid_id_dedupe_on_collision() -> None:
    doc = {
        "version": 1,
        "trace": [
            {"node": "a:b", "kind": "user", "text_preview": "one"},
            {"node": "a/b", "kind": "assistant"},  # sanitizes to the same a_b
        ],
    }
    lines = dsl_to_mermaid(doc).splitlines()
    assert lines[1] == '    a_b["User: one"]'
    assert lines[2] == '    a_b_1["Assistant"]'
    assert lines[3] == "    a_b --> a_b_1"


@pytest.mark.parametrize("fmt", ["rich", ""])
def test_cli_rejects_unsupported_format(fmt: str) -> None:
    from typer.testing import CliRunner

    from deepmentor_cli.main import app

    result = CliRunner().invoke(app, ["session", "trace", "s1", "--format", fmt])
    assert result.exit_code == 1
    assert "Unsupported format" in result.output


def test_cli_mermaid_print_survives_rich_markup_in_user_text(monkeypatch) -> None:
    # #75: user text like "[/b]" is a rich closing tag — printing the
    # mermaid export used to raise MarkupError and crash the CLI.
    from deepmentor_cli import session_cmd

    class _StubApp:
        async def get_session(self, session_id: str) -> dict:
            return {
                "messages": [
                    _msg(1, "user", None, content="how do I write [/b] in markdown?"),
                ]
            }

    monkeypatch.setattr(session_cmd, "DeepMentorApp", _StubApp)
    from typer.testing import CliRunner

    from deepmentor_cli.main import app

    result = CliRunner().invoke(app, ["session", "trace", "s1", "--format", "mermaid"])
    assert result.exit_code == 0
    assert "[/b]" in result.output
